- name: Uninstall php
  yum: name={{ item }} state=absent enablerepo=remi,remi-php56
  with_items:
    - php-suhosin
    - php-pecl-xdebug
    - php56-php-cli
    - php56-php-common
    - php56-php-pear
    - php56-php-pecl-igbinary
    - php56-php-pecl-jsonc
    - php56-php-pecl-redis
    - php56-php-pecl-zip
    - php56-php-pecl-redis
    - php56-php-process
    - php56-php-xml
    - php56-runtime

- name: Install php56
  yum: name={{ item }} state=present enablerepo=remi-php56
  with_items:
    - php
    - php-cli
    - php-common
    - php-devel
    - php-fpm
    - php-gd
    - php-intl
    - php-mbstring
    - php-mcrypt
    - php-mysqlnd
    - php-opcache
    - php-pdo
    - php-pgsql
    - php-soap
    - php-xml
    - php-pecl-memcache
    - php-pecl-memcached
    - php-pecl-xhprof
    - php-pecl-redis

- lineinfile: "dest=/etc/php.ini backup=yes state=present regexp='^date.timezone' line='date.timezone = Asia/Ho_Chi_Minh'"
- lineinfile: "dest=/etc/php.ini backup=yes state=present regexp='^post_max_size' line='post_max_size = 10M'"
- lineinfile: "dest=/etc/php.ini backup=yes state=present regexp='^upload_max_filesize' line='upload_max_filesize = 10M'"

- copy: backup=yes src=www.conf dest=/etc/php-fpm.d/www.conf

- file: path=/var/log/php-fpm/ mode=0755

- service: name=php-fpm state=restarted enabled=yes